### ISSUE TITLE
Add drop_type_if_exists/2

### ISSUE THREAD

**Issue by thiamsantos** [brainn-co/ecto_enum_migration#2]
## Motivation

We need to support the if exists options of the [`DROP TYPE` statement](https://www.postgresql.org/docs/9.1/sql-droptype.html) in order to have a more complete DSL.

## Proposed solution

Introduce `drop_type_if_exists/2` function.

Below some example of the function and the generated SQL.

```elixir
drop_type_if_exists(:status)
# DROP TYPE IF EXISTS "public.status";
drop_type_if_exists(:status, schema: "custom_schema")
# DROP TYPE IF EXISTS "custom_schema.status";
```

**Comment by antedeguemon** [comment]
What is your opinion about also adding a `if_exists` option to `drop_type/2`, since it is a parameter for `DROP TYPE`?
Other possible options for `drop_type/2` could be all possible parameters for `DROP TYPE` ([see here](https://www.postgresql.org/docs/current/sql-droptype.html)). Does it make sense?

**Comment by thiamsantos** [comment]
I think that makes sense @antedeguemon . In a way I was trying to mimic the API from ecto https://hexdocs.pm/ecto_sql/Ecto.Migration.html#drop_if_exists/1. But, I think your suggestion would be better.
We could also support a `on_delete` option for the `CASCADE`/`RESTRICT` options.
